name: Approve version bump pull request

on:
  pull_request:
    types:
      - opened
      
jobs:
  autoapprove:
    name: Auto approve a PR from a bump_version branch
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
