name: Approve version bump pull request

on:
  pull_request:
    types:
      - opened
      
jobs:
  autoapprove:
    name: Auto approve PR from bump_version
    if: startsWith(github.head_ref, 'bump_version')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
  automerge:
    name: Auto merge after approval
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "merge"
          MERGE_LABELS: ""
          MERGE_DELETE_BRANCH: "true"
  autotag:
    name: Tag master
    needs: automerge
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Read version file
        id: getversion
        run: echo "version=$(cat version)" >> $GITHUB_OUTPUT
      - name: git commands
        run: |
          cd ${{runner.workspace}}/potku
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo "${{ steps.getversion.outputs.version }}"
          git tag -a "${{ steps.getversion.outputs.version }}" -m "Automatic tag for version ${{ steps.getversion.outputs.version }}"
          git push origin "${{ steps.getversion.outputs.version }}"
    
