name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: run windows script
        if: ${{ matrix.os }} == 'windows-latest'
        run: |
          ${{runner.workspace}}\potku\build.bat
      - name: run linux script
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          ${{runner.workspace}}\potku\build.sh
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ${{runner.workspace}}/external/bin
