name: Build

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: run windows script
        run: |
          ${{runner.workspace}}\potku\build.bat
      - name: Archive windows build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-windows
          path: ${{runner.workspace}}/potku/external/bin
          
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: run linux script
      run: |
        sudo apt-get install -y libgsl27 libgsl-dev
        ${{runner.workspace}}/potku/build.sh
        cd ${{runner.workspace}}/potku
        curl http://users.jyu.fi/~jaakjuli/jibal/data/data.tar.gz -o data.tar.gz && tar -xvf data.tar.gz -C external/share/jibal
    - name: build Potku
      run: |
        cd ${{runner.workspace}}/potku
        pip install pipenv
        pipenv install
        pipenv run install pyinstaller
        pipenv run pyinstaller potku.spec
    - name: Archive linux build
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-linux
        path: ${{runner.workspace}}/potku/dist
