name: Compile_C

on:
  workflow_dispatch:

jobs:   
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: repo
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v5
      id: vcpkg
      with:
        pkgs: gsl getopt
        triplet: x64-windows
        cache-key: windows
        revision: master
        token: ${{ github.token }}
    - name: Set environment + run script
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set VCPKG_ROOT ${{ runner.workspace }}\potku\vcpkg
        set VCPKG_DEFAULT_TRIPLET x64-windows
        cd ${{runner.workspace}}\potku\repo
        build.bat
    - name: Archive windows build
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-windows
        path: ${{runner.workspace}}\potku\repo\external\bin
        
