name: Compile C apps

on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build linux executables
      run: |
        sudo apt-get install -y libgsl27 libgsl-dev
        cd ${{runner.workspace}}/potku/dev
        ./build.sh
    - name: Archive linux executables
      uses: actions/upload-artifact@v3
      with:
        name: c-apps-linux
        path: |
          ${{runner.workspace}}/potku/external/bin
          ${{runner.workspace}}/potku/external/lib
  
  build_macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build MacOS executables
      run: |
        brew install cmake
        brew install gsl
        cd ${{runner.workspace}}/potku/dev
        ./build.sh
    - name: Archive macos executables
      uses: actions/upload-artifact@v3
      with:
        name: c-apps-macos
        path: |
          ${{runner.workspace}}/potku/external/bin
          ${{runner.workspace}}/potku/external/lib
        
