# Intended to run as a sub-workflow in version_bump.yml
name: Compile C apps

on:
  [workflow_call, workflow_dispatch]
  
jobs:
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: repo
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: gsl getopt
        triplet: x64-windows
        cache-key: windows
        revision: master
        token: ${{ github.token }}
        github-binarycache: true
    - name: Set environment + build executables
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set VCPKG_ROOT ${{ runner.workspace }}\potku\vcpkg
        set VCPKG_DEFAULT_TRIPLET x64-windows
        cd ${{runner.workspace}}\potku\repo\dev
        build.bat ${{ runner.workspace }}\potku\vcpkg\scripts\buildsystems\vcpkg.cmake
    - name: Archive windows executables
      uses: actions/upload-artifact@v4
      with:
        name: c-apps-windows-${{runner.arch}}
        path: |
          ${{runner.workspace}}\potku\repo\external\bin
          ${{runner.workspace}}\potku\repo\external\share

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build linux executables
      run: |
        sudo apt-get install -y libgsl27 libgsl-dev
        cd ${{runner.workspace}}/potku/dev
        ./build.sh
    - name: Archive linux executables
      uses: actions/upload-artifact@v4
      with:
        name: c-apps-linux-${{runner.arch}}
        path: |
          ${{runner.workspace}}/potku/external/bin
          ${{runner.workspace}}/potku/external/lib
          ${{runner.workspace}}/potku/external/share

  build_macos:
    strategy:
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build MacOS executables
      run: |
        brew install cmake
        brew install gsl
        brew install libomp
        cd ${{runner.workspace}}/potku/dev
        ./build.sh
    - name: Archive macos executables
      uses: actions/upload-artifact@v4
      with:
        name: c-apps-macos-${{runner.arch}}
        path: |
          ${{runner.workspace}}/potku/external/bin
          ${{runner.workspace}}/potku/external/lib
          ${{runner.workspace}}/potku/external/share