name: Package Potku

on:
  workflow_call:

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Read version file
        id: get_content
        run: |
          cd ${{runner.workspace}}/potku
          echo "version=$(awk 'NR==1' version.txt)" >> $GITHUB_OUTPUT
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_content.outputs.version }}
          release_name: Potku ${{ steps.get_content.outputs.version }}
          draft: false
          prerelease: false
  
  package_windows:
    needs: create_release
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download C artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: c-apps-windows
          workflow: version_bump.yml
          path: ${{runner.workspace}}/potku/external/bin
          search_artifacts: true
      - name: Collect external files
        run: |
          mkdir ${{runner.workspace}}\potku\external\share\jibal
          curl http://users.jyu.fi/~jaakjuli/jibal/data/data.tar.gz -o data.tar.gz && tar -xvf data.tar.gz -C ${{runner.workspace}}\potku\external\share\jibal
          cd ${{runner.workspace}}\potku\external\bin
          curl -L https://gnuwin32.sourceforge.net/downlinks/gawk-bin-zip.php -o gawk.zip
          tar -xf gawk.zip -C ${{runner.workspace}}\potku\external\bin bin/awk.exe
          move ${{runner.workspace}}\potku\external\bin\bin\awk.exe ${{runner.workspace}}\potku\external\bin
          rmdir bin
          del gawk.zip
          cd ${{runner.workspace}}\potku\external\share
          curl https://www.jyu.fi/science/en/physics/research/infrastructures/accelerator-laboratory/pelletron/potku/release_versions/potku_mac_20220331.zip/@@download/file/potku_mac_20220331.zip -o potku.zip
          tar -xf potku.zip -C ${{runner.workspace}}\potku\external\share potku/external/share/srim2013.tot
          tar -xf potku.zip -C ${{runner.workspace}}\potku\external\share potku/external/share/jibal/abundances.dat
          tar -xf potku.zip -C ${{runner.workspace}}\potku\external\share potku/external/share/jibal/masses.dat
          move ${{runner.workspace}}\potku\external\share\potku\external\share\srim2013.tot ${{runner.workspace}}\potku\external\share
          move ${{runner.workspace}}\potku\external\share\potku\external\share\jibal\abundances.dat ${{runner.workspace}}\potku\external\share\jibal
          move ${{runner.workspace}}\potku\external\share\potku\external\share\jibal\masses.dat ${{runner.workspace}}\potku\external\share\jibal
          rmdir potku
          del potku.zip
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Package Potku
        run: |
          cd ${{runner.workspace}}/potku
          pip install pipenv
          pipenv install
          pipenv run pip install pyinstaller
          pipenv run pyinstaller potku.spec
      - name: Create archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Potku-Windows.zip'
          directory: ${{runner.workspace}}/potku/dist
          path: potku
      - name: Upload Windows build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/potku/dist/Potku-Windows.zip
          asset_name: Potku-Windows.zip
          asset_content_type: application/zip
      
          
  package_linux:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download C artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: c-apps-linux
          workflow: compile_c_apps.yml
          path: ${{runner.workspace}}/potku/external
          search_artifacts: true
      - name: Collect external files
        run: |
          mkdir -p ${{runner.workspace}}/potku/external/share/jibal
          curl http://users.jyu.fi/~jaakjuli/jibal/data/data.tar.gz -o data.tar.gz && tar -xvf data.tar.gz -C ${{runner.workspace}}/potku/external/share/jibal
          cd ${{runner.workspace}}/potku/external/share
          curl https://www.jyu.fi/science/en/physics/research/infrastructures/accelerator-laboratory/pelletron/potku/release_versions/potku_mac_20220331.zip/@@download/file/potku_mac_20220331.zip -o potku.zip
          unzip potku.zip 'potku/external/share/srim2013.tot' -d ${{runner.workspace}}/potku/external/share
          unzip potku.zip 'potku/external/share/jibal/abundances.dat' -d ${{runner.workspace}}/potku/external/share
          unzip potku.zip 'potku/external/share/jibal/masses.dat' -d ${{runner.workspace}}/potku/external/share
          mv ${{runner.workspace}}/potku/external/share/potku/external/share/srim2013.tot ${{runner.workspace}}/potku/external/share/srim2013.tot
          mv ${{runner.workspace}}/potku/external/share/potku/external/share/jibal/abundances.dat ${{runner.workspace}}/potku/external/share/jibal/abundances.dat
          mv ${{runner.workspace}}/potku/external/share/potku/external/share/jibal/masses.dat ${{runner.workspace}}/potku/external/share/jibal/masses.dat
          rm -r potku
          rm potku.zip 
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Package Potku
        run: |
          cd ${{runner.workspace}}/potku
          pip install pipenv
          pipenv install
          pipenv run pip install pyinstaller
          pipenv run pyinstaller potku.spec
      - name: Create archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Potku-Linux.zip'
          directory: ${{runner.workspace}}/potku/dist
          path: potku
      - name: Upload Linux build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/potku/dist/Potku-Linux.zip
          asset_name: Potku-Linux.zip
          asset_content_type: application/zip
  
  package_macos:
    runs-on: macos-latest
    needs: create_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download C artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: c-apps-macos
          workflow: compile_c_apps.yml
          path: ${{runner.workspace}}/potku/external
          search_artifacts: true
      - name: Collect external files
        run: |
          mkdir -p ${{runner.workspace}}/potku/external/share/jibal
          curl http://users.jyu.fi/~jaakjuli/jibal/data/data.tar.gz -o data.tar.gz && tar -xvf data.tar.gz -C ${{runner.workspace}}/potku/external/share/jibal
          cd ${{runner.workspace}}/potku/external/share
          curl https://www.jyu.fi/science/en/physics/research/infrastructures/accelerator-laboratory/pelletron/potku/release_versions/potku_mac_20220331.zip/@@download/file/potku_mac_20220331.zip -o potku.zip
          unzip potku.zip 'potku/external/share/srim2013.tot' -d ${{runner.workspace}}/potku/external/share
          unzip potku.zip 'potku/external/share/jibal/abundances.dat' -d ${{runner.workspace}}/potku/external/share
          unzip potku.zip 'potku/external/share/jibal/masses.dat' -d ${{runner.workspace}}/potku/external/share
          mv ${{runner.workspace}}/potku/external/share/potku/external/share/srim2013.tot ${{runner.workspace}}/potku/external/share/srim2013.tot
          mv ${{runner.workspace}}/potku/external/share/potku/external/share/jibal/abundances.dat ${{runner.workspace}}/potku/external/share/jibal/abundances.dat
          mv ${{runner.workspace}}/potku/external/share/potku/external/share/jibal/masses.dat ${{runner.workspace}}/potku/external/share/jibal/masses.dat
          rm -r potku
          rm potku.zip 
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Package Potku
        run: |
          cd ${{runner.workspace}}/potku
          pip install pipenv
          pipenv install
          pipenv run pip install pyinstaller
          pipenv run pyinstaller potku.spec
      - name: Create archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Potku-macOS.zip'
          directory: ${{runner.workspace}}/potku/dist
          path: potku
      - name: Upload MacOS build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/potku/dist/Potku-macOS.zip
          asset_name: Potku-macOS.zip
          asset_content_type: application/zip
