name: Package Potku

on:
  workflow_dispatch:

jobs:  
  package_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download C artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-artifact-windows
          workflow: compile_c_apps.yml
          path: ${{runner.workspace}}/potku/external/bin
      - name: Collect external files
        run: |
          mkdir -p ${{runner.workspace}}/potku/external/share/jibal
          curl http://users.jyu.fi/~jaakjuli/jibal/data/data.tar.gz -o data.tar.gz && tar -xvf data.tar.gz -C ${{runner.workspace}}/potku/external/share/jibal
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Package Potku
        run: |
          cd ${{runner.workspace}}/potku
          pip install pipenv
          pipenv install
          pipenv run pip install pyinstaller
          pipenv run pyinstaller potku.spec
      - name: Archive Windows build
        uses: actions/upload-artifact@v3
        with:
          name: Potku-windows
          path: ${{runner.workspace}}/potku/dist
      
          
  package_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download C artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-artifact-linux
          workflow: compile_c_apps.yml
          path: ${{runner.workspace}}/potku/external/bin
      - name: check dirs
        run: |
          cd ${{runner.workspace}}
          sudo tree -a
      - name: Collect external files
        run: |
          mkdir -p ${{runner.workspace}}/potku/external/share/jibal
          curl http://users.jyu.fi/~jaakjuli/jibal/data/data.tar.gz -o data.tar.gz && tar -xvf data.tar.gz -C ${{runner.workspace}}/potku/external/share/jibal
      - name: Package Potku
        run: |
          cd ${{runner.workspace}}/potku
          pip install pipenv
          pipenv install
          pipenv run install pyinstaller
          pipenv run pyinstaller potku.spec
      - name: Archive Linux build
        uses: actions/upload-artifact@v3
        with:
          name: Potku-Linux
          path: ${{runner.workspace}}/potku/dist
