# Intended to run as a sub-workflow inside bump_version.yml.
name: Package Potku

on:
  workflow_call:

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Read version file
        id: get_content
        run: |
          cd ${{runner.workspace}}/potku
          echo "version=$(awk 'NR==1' version.txt)" >> $GITHUB_OUTPUT
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_content.outputs.version }}
          release_name: Potku ${{ steps.get_content.outputs.version }}
          draft: false
          prerelease: false
  
  package_windows:
    needs: create_release
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download C artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: c-apps-windows
          workflow: version_bump.yml
          path: ${{runner.workspace}}/potku/external/bin
          search_artifacts: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Collect external files and package Potku
        run: |
          cd ${{runner.workspace}}/potku
          pip install pipenv
          pipenv install
          cd ${{runner.workspace}}/potku/dev
          pipenv run external_file_manager.py fetch
          cd ${{runner.workspace}}/potku
          pipenv run pip install pyinstaller
          pipenv run pyinstaller potku.spec
      - name: Create archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Potku-Windows.zip'
          directory: ${{runner.workspace}}/potku/dist
          path: potku
      - name: Upload Windows build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/potku/dist/Potku-Windows.zip
          asset_name: Potku-Windows.zip
          asset_content_type: application/zip
      
          
  package_linux:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download C artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: c-apps-linux
          workflow: version_bump.yml
          path: ${{runner.workspace}}/potku/external
          search_artifacts: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Collect external files and package Potku
        run: |
          cd ${{runner.workspace}}/potku
          pip install pipenv
          pipenv install
          cd ${{runner.workspace}}/potku/dev
          pipenv run external_file_manager.py fetch
          cd ${{runner.workspace}}/potku
          pipenv run pip install pyinstaller
          pipenv run pyinstaller potku.spec
      - name: Create archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Potku-Linux.zip'
          directory: ${{runner.workspace}}/potku/dist
          path: potku
      - name: Upload Linux build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/potku/dist/Potku-Linux.zip
          asset_name: Potku-Linux.zip
          asset_content_type: application/zip
  
  package_macos:
    runs-on: macos-latest
    needs: create_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download C artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: c-apps-macos
          workflow: version_bump.yml
          path: ${{runner.workspace}}/potku/external
          search_artifacts: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
      - name: Collect external files and package Potku
        run: |
          cd ${{runner.workspace}}/potku
          pip install pipenv
          pipenv install
          cd ${{runner.workspace}}/potku/dev
          pipenv run external_file_manager.py fetch
          cd ${{runner.workspace}}/potku
          pipenv run pip install pyinstaller
          pipenv run pyinstaller potku.spec
      - name: Create archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Potku-macOS.zip'
          directory: ${{runner.workspace}}/potku/dist
          path: potku
      - name: Upload MacOS build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}/potku/dist/Potku-macOS.zip
          asset_name: Potku-macOS.zip
          asset_content_type: application/zip
