name: Bump version

on:
  pull_request:
    types:
      - opened
      
jobs:
  
  # Run only for branches that start with pattern 'bump_version'
  # This job checks if only version.txt changed and pull request
  # creator has write permission.
  branch_verification:
    name: Verify branch and only version.txt changed
    if: startsWith(github.head_ref, 'bump_version')
    runs-on: ubuntu-latest
    outputs:
      verification_passed: ${{ steps.compare.outputs.verification_passed }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        # Check if creator of pull request has write permission
      - name: Verify user
        id: check_user
        uses: actions-cool/check-user-permission@v2.2.0
        with:
          require: 'write'
        # Check changed files between master and pull request head
      - name: Get diff of head to master
        id: get_diff
        uses: tj-actions/changed-files@v36
        # Check passed if only version.txt changed and user has write permission
      - name: Compare diff
        id: compare
        if: |
          steps.get_diff.outputs.all_changed_files == 'version.txt' &&
          steps.check_user.outputs.require-result == 'true'
        run: |
          echo "verification_passed=true" >> $GITHUB_OUTPUT
  
  # If branch_verification job returns true then the pull request
  # is automatically approved by github-actions-bot.
  auto_approve:
    name: Auto approve PR from bump_version
    needs: branch_verification
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: needs.branch_verification.outputs.verification_passed == 'true'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
  # Automatically merge the approved version bump pull request. Version
  # bump branch is automatically deleted after merging.
  auto_merge:
    name: Auto merge after approval
    needs: [branch_verification, auto_approve]
    runs-on: ubuntu-latest
    if: needs.branch_verification.outputs.verification_passed == 'true'
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: "merge"
          MERGE_LABELS: ""
          MERGE_DELETE_BRANCH: "true"
  
  # Automatically create an annotated tag of master branch after
  # merging version bump pull request.
  auto_tag:
    name: Tag master
    needs: [branch_verification, auto_approve, auto_merge]
    runs-on: ubuntu-latest
    if: needs.branch_verification.outputs.verification_passed == 'true'
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive
      - name: Read version file
        id: getversion
        run: |
          cd ${{runner.workspace}}/potku
          echo "version=$(awk 'NR==1' version.txt)" >> $GITHUB_OUTPUT
      - name: git commands
        run: |
          cd ${{runner.workspace}}/potku
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag -a "${{ steps.getversion.outputs.version }}" -m "Automatic tag for version ${{ steps.getversion.outputs.version }}"
          git push origin "${{ steps.getversion.outputs.version }}"
    
